export const CONTACT_FORM_SUBMIT_INIT = 'CONTACT_FORM_SUBMIT_INIT';
export const CONTACT_FORM_SUBMIT_SUCCESS = 'CONTACT_FORM_SUBMIT_SUCCESS';
export const CONTACT_FORM_SUBMIT_ERROR = 'CONTACT_FORM_SUBMIT_ERROR';